"""Add assignee to StockMovement

Revision ID: 2dc37b88edc7
Revises: d2758bd5ea55
Create Date: 2026-02-17 15:51:57.235539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc37b88edc7'
down_revision: Union[str, Sequence[str], None] = 'd2758bd5ea55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stockmovement', sa.Column('assignee', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stockmovement', 'assignee')
    # ### end Alembic commands ###
