"""Add supplier_id to Product

Revision ID: 46bab47eda92
Revises: 2cfd61003c6e
Create Date: 2026-02-17 15:09:23.660772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46bab47eda92'
down_revision: Union[str, Sequence[str], None] = '2cfd61003c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'supplier', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'supplier_id')
    # ### end Alembic commands ###
