"""Add min_stock to Product

Revision ID: d2758bd5ea55
Revises: 46bab47eda92
Create Date: 2026-02-17 15:16:48.427839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2758bd5ea55'
down_revision: Union[str, Sequence[str], None] = '46bab47eda92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('min_stock', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'min_stock')
    # ### end Alembic commands ###
